@BaseUrl = http://localhost:3000
@AccessToken = 

### Login
GET {{BaseUrl}}/login?isLimitedAccess=true
Accept: application/json

#### Proxy ProductAPI
GET {{BaseUrl}}/api/product
Authorization: Bearer {{AccessToken}}

#### Proxy OrderAPI
GET {{BaseUrl}}/api/order
Authorization: Bearer {{AccessToken}}

#### Mail
POST {{BaseUrl}}/mail HTTP/1.1
Content-Type: application/json
{
  "email": "test@test.com",
  "title": "Welcome to our newsletter!",
  "content": "Thank you for subscribing to our newsletter!"
}