@BaseUrl = http://localhost:3000
@AccessToken =

### Login
GET {{BaseUrl}}/login?isLimitedAccess=true
Accept: application/json

#### Proxy ProductAPI
GET {{BaseUrl}}/api/product
Authorization: Bearer {{AccessToken}}

#### Proxy OrderAPI
GET {{BaseUrl}}/api/order
Authorization: Bearer {{AccessToken}}
